export const AGROVOC_KEYWORDS = [
    "Abastecimiento de agua",
    "Acceso a la información",
    "Acceso a las finanzas",
    "Acceso a los alimentos",
    "Acceso al mercado",
    "Aceleración",
    "Acuerdo comercial",
    "Acuerdos",
    "Acuerdos comerciales",
    "Acuerdos económicos",
    "Acuerdos internacionales",
    "Acuicultura",
    "Adaptación",
    "Adaptación al cambio climático",
    "Administración",
    "Administración de empresas",
    "Administración de recursos",
    "Adopción de tecnología",
    "Agave",
    "Agricultores",
    "Agricultura",
    "Agricultura climáticamente inteligente",
    "Agricultura digital",
    "Agricultura familiar",
    "Agricultura orgánica",
    "Agricultura sostenible",
    "Agricultura tropical",
    "Agricultura vertical",
    "Agrobiodiversidad",
    "Agroecosistema",
    "Agroindustria",
    "Agroquímicos",
    "Agroturismo",
    "Agua",
    "Agua potable",
    "Alagoas",
    "Alianzas",
    "Alimentación del ganado",
    "Alimentación escolar",
    "Alimento para niño",
    "Alimentos",
    "Almacenamiento de agua",
    "Alta mar",
    "Amazonas (brasil)",
    "Ambiente",
    "Ambiente marino",
    "América del sur",
    "América latina y el caribe",
    "Análisis de la cadena de valor",
    "Antimicrobianos",
    "Aphididae",
    "Apicultura",
    "Apoyo a la investigación",
    "Aprendizaje",
    "Aprovechamiento comercial",
    "Archivos",
    "Arroz",
    "Arrozales",
    "Asistencia técnica",
    "Asociación sectores público y privado",
    "Auditoría",
    "Aumento de producción",
    "Aves de corral",
    "Avicultura",
    "Ayuda al desarrollo",
    "Ayuda alimentaria",
    "Banano",
    "Banco de germoplasma",
    "Base de datos",
    "Batata",
    "Bbioeconomía",
    "Bienestar rural",
    "Biochar",
    "Biociencia",
    "Biodiversidad",
    "Biodiversidad forestal",
    "Biogás",
    "Biopesticidas",
    "Bioplaguicidas",
    "Bioseguridad",
    "Biotecnología",
    "Biotecnología animal",
    "Bonos",
    "Bosques",
    "Buenas prácticas agrícolas",
    "Buenas prácticas agrícolas",
    "Cabra",
    "Cabras lecheras",
    "Cacao",
    "Cadena alimentaria",
    "Cadenas de valor",
    "Cadenas de valor agrícolas",
    "Cadmio",
    "Café",
    "Calidad",
    "Calidad de la fruta",
    "Calidad de la madera",
    "Calidad de la semilla",
    "Calidad de los alimentos",
    "Calidad de vida",
    "Calidad del agua",
    "Calidad del cultivo",
    "Calidad del producto",
    "Cambio climático",
    "Cambio tecnológico",
    "Camélidos",
    "Caña de azúcar",
    "Capacidad de aprendizaje",
    "Capacidad de producción",
    "Capacidad empresarial",
    "Capacitación",
    "Capacitación agricola",
    "Capacitatión en temas de género",
    "Capital humano",
    "Captación del agua de lluvia",
    "Carbono",
    "Caribe",
    "Cartografía",
    "Catastros",
    "Centroamérica",
    "Centros de capacitación",
    "Cerdo",
    "Certificación de semillas",
    "Chocolate",
    "Chrysomya",
    "Cicadellidae",
    "Ciencia",
    "Ciencia ciudadana",
    "Ciencias agrícolas",
    "Ciencias ambientales",
    "Científicos",
    "Ciruela",
    "Clima",
    "Clima semiárido",
    "Clon",
    "Coccoidea",
    "Coco",
    "Codex alimentarius",
    "Coffea",
    "Colección de datos",
    "Colletotrichum acutatum",
    "Comercialización",
    "Comercialización agrícola",
    "Comercialización cooperativa",
    "Comercio agrícola",
    "Comercio exterior",
    "Comercio interior",
    "Comercio internacional",
    "Competencia económica",
    "Comportamiento competitivo",
    "Compost",
    "Compra",
    "Comunicación",
    "Comunidad del caribe",
    "Comunidades agrícolas",
    "Comunidades pesqueras costeras",
    "Comunidades rurales",
    "Condiciones de vida",
    "Condiciones del medio ambiente",
    "Conservación (almacenamiento)",
    "Conservación de aguas",
    "Conservación de la diversidad biológica",
    "Conservación de la naturaleza",
    "Conservación de los recursos",
    "Conservación de suelos",
    "Conservación del ecosistema",
    "Construcción",
    "Consultorías",
    "Consumidores",
    "Consumo",
    "Consumo de alimentos",
    "Contabilidad",
    "Contaminación",
    "Contaminantes",
    "Contenido de agua en el suelo",
    "Control de enfermedades",
    "Control de malezas",
    "Control de plagas",
    "Control integrado de plagas",
    "Control reproducción (animal)",
    "Cooperación",
    "Cooperación público-privada",
    "Cooperación sur-sur",
    "Coordinación",
    "Corredor seco",
    "Costa",
    "Covid-19",
    "Creación de capacidad",
    "Cuencas hidrográficas",
    "Cultivo en agua",
    "Cultivos",
    "Cultivos de insectos",
    "Cumplimiento",
    "Curso de formación",
    "Cursos de capacitación",
    "Dalbulus maidis",
    "Datos de producción",
    "Datos personales",
    "Degradación del suelo",
    "Demanda del mercado",
    "Desalinización del agua",
    "Desarrollo agrícola",
    "Desarrollo de capacidad",
    "Desarrollo de la comunidad",
    "Desarrollo de recursos",
    "Desarrollo económico",
    "Desarrollo institucional",
    "Desarrollo integral",
    "Desarrollo regional",
    "Desarrollo rural",
    "Desarrollo rural integrado",
    "Desarrollo social",
    "Desarrollo sostenible",
    "Desarrollo urbano",
    "Desastres causados por el hombre",
    "Desastres naturales",
    "Descentralización",
    "Desertificación",
    "Destrucción de hábitat",
    "Detección",
    "Diagnóstico de laboratorio",
    "Difusión de información",
    "Dirección de proyectos",
    "Directriz",
    "Diseminación de semillas",
    "Diseño",
    "Diseño de proyectos",
    "Diversificación",
    "Diversificación de modos de vida",
    "Donaciones para la investigación",
    "Ecología",
    "Econometría",
    "Economía",
    "Economía agrícola",
    "Economía circular",
    "Economía de bienestar",
    "Economía de la producción",
    "Economía forestal",
    "Economía rural",
    "Economías mixtas",
    "Ecosistema",
    "Ecosistemas marinos",
    "Educación",
    "Educación agraria",
    "Educación nutricional",
    "Educación pública",
    "Educación secundaria",
    "Eficiencia de uso del nitrógeno",
    "Eficiencia del riego",
    "Eficiencia energética",
    "Emergencia",
    "Emisiones de gases de efecto invernadero",
    "Empleo",
    "Empleo rural",
    "Empresas",
    "Empresas pequeñas",
    "Empresas pequeñas y medianas",
    "Energía renovable",
    "Enfermedades de las plantas",
    "Enfermedades de los animales",
    "Enfermedades endémicas",
    "Enfermedades transmitidas por agua",
    "Enfoque de paisajes",
    "Enfoques participativos",
    "Engorde",
    "Ensayo de semillas",
    "Enseñanza",
    "Epidemiología",
    "Equidad de género",
    "Equipo",
    "Equipo móvil",
    "Erradicación de enfermedades",
    "Erradicación de plagas",
    "Escuela de campo para agricultores",
    "Escuelas",
    "Especie silvestre afín a las plantas cultivadas",
    "Especies exóticas",
    "Estrategias",
    "Estrategías de desarrollo rural",
    "Estructura social",
    "Estudiantes",
    "Estudios de factibilidad",
    "Evacuación de aguas residuales",
    "Evaluación",
    "Evaluación de la sostenibilidad",
    "Evaluación de proyectos",
    "Evaluación de riesgos",
    "Evento meteorológico extremo",
    "Explotación agrícola intensiva",
    "Explotación en pequeña escala",
    "Explotación ilegal de madera",
    "Exportaciones",
    "Exportaciones hortícolas",
    "Extensión",
    "Extensión agrícola",
    "Fabricación de alimentos",
    "Fábricas",
    "Factores antropogénicos",
    "Familia (taxón)",
    "Fertilización",
    "Financiamiento",
    "Finanza",
    "Finanzas rurales",
    "Fincas",
    "Fitosanidad",
    "Fondo para el medio ambiente mundial",
    "Formación profesional",
    "Foros",
    "Fortalecimiento de las capacidades",
    "Fortalecimiento institucional",
    "Fríjol",
    "Frutas",
    "Fusarium",
    "Fusarium oxysporum",
    "Ganadería",
    "Ganadería lechera",
    "Ganado bovino",
    "Garantías de la inversión",
    "Gases de efecto invernadero",
    "Gastronomía",
    "Generación de ingresos",
    "Género",
    "Germoplasma",
    "Gestión",
    "Gestión ambiental",
    "Gestión de la información",
    "Gestión de recursos humanos",
    "Gestión de riesgos",
    "Gestión del agua",
    "Gestión del conocimiento",
    "Gestión integrada",
    "Gestión participativa",
    "Gobernanza",
    "Gobernanza de la cadena de valor",
    "Gobernanza del agua",
    "Gobernanza forestal",
    "Granos",
    "Herramientas de apoyo a la toma de decisiones",
    "Hierro",
    "Higiene de los alimentos",
    "Hongo patógeno",
    "Horticultura",
    "Huella de carbono",
    "Huertos",
    "Humedales",
    "Igualdad de género",
    "Imágen por satélite",
    "Implementación",
    "Implementación nacional",
    "Importaciones",
    "Incentivos",
    "Inclusión",
    "Inclusión financiera",
    "Inclusión social",
    "Incubación de abejas",
    "Indemnización",
    "Industria alimentaria",
    "Industria azucarera",
    "Industria cafetera",
    "Industria de semillas",
    "Industria tabacalera",
    "Informes",
    "Infraestructura",
    "Ingreso familiar",
    "Iniciativas",
    "Innovación",
    "Innovación agrícola",
    "Innovación financiera",
    "Inocuidad alimentaria",
    "Inseguridad alimentaria",
    "Inspección",
    "Inspección de los alimentos",
    "Instituciones",
    "Instituciones públicas",
    "Insumos agricolas",
    "Integración",
    "Integración económica",
    "Intercambio de conocimientos",
    "Inundación",
    "Inversión pública",
    "Inversiones",
    "Investigación agrícola para el desarrollo",
    "Investigación científica",
    "Investigación de mercados",
    "Irrigación",
    "Jalisco",
    "Juventud",
    "Juventud rural",
    "Larvas de insectos",
    "Latinoamérica",
    "Leche",
    "Legislación",
    "Legislación agraria",
    "Legislación alimentaria",
    "Leyes",
    "Lepidoptera",
    "Liderazgo",
    "Limites máximos de residuos",
    "Logística",
    "Madera",
    "Madera de construcción",
    "Maíz",
    "Manejo de nutrientes",
    "Manejo del cultivo",
    "Manejo del ganado",
    "Manejo del suelo",
    "Manejo forestal",
    "Mangles",
    "Marchitez",
    "Mataderos",
    "Materia orgánica",
    "Materiales",
    "Mecanismos de acción",
    "Medicamentos veterinarios",
    "Medidas fitosanitarias",
    "Medio ambiente",
    "Medios de vida",
    "Medios de vida sostenibles",
    "Mejora de cultivos",
    "Mejora genética",
    "Mejoramiento animal",
    "Mejoramiento genético",
    "Mercado interior",
    "Mercados",
    "Metano",
    "Metodología",
    "Métodos de cultivo",
    "Métodos de riego",
    "Michoacán",
    "Microeconomía",
    "Microempresas",
    "Miel",
    "Mitigación",
    "Mitigación de riesgos",
    "Mitigación del cambio climático",
    "Modelos",
    "Modelos de negocio",
    "Monitoreo",
    "Mosca de la fruta",
    "Movimiento del agua en el suelo",
    "Mujeres",
    "Mujeres rurales",
    "Mujeres rurales",
    "Musa (plátanos)",
    "Musaceae",
    "Nanotecnología",
    "Necesidades de educación",
    "Negociación",
    "Negocios",
    "Nivel de vida",
    "Normalización",
    "Normas",
    "Normas alimentarías",
    "Nutrición",
    "Nutrientes",
    "Oaxaca",
    "Objetivo 1 fin de la pobreza",
    "Objetivo 10 reducción de las desigualdades",
    "Objetivo 11 ciudades y comunidades sostenibles",
    "Objetivo 12 producción y consumo responsables",
    "Objetivo 13 acción por el clima",
    "Objetivo 16 paz, justicia e instituciones sólidas",
    "Objetivo 17 alianzas para lograr los objetivos",
    "Objetivo 2 hambre cero",
    "Objetivo 3 salud y bienestar",
    "Objetivo 4 educación de calidad",
    "Objetivo 5 igualdad de género",
    "Objetivo 6 agua limpia y saneamiento",
    "Objetivo 8 trabajo decente y crecimiento económico",
    "Objetivo 9 industria, innovación e infraestructuras",
    "Olivo",
    "Ordenación de aguas",
    "Ordenación de recursos",
    "Ordenación de recursos naturales",
    "Organismo nativo",
    "Organización del trabajo",
    "Paisaje",
    "Paisaje agrícola",
    "Pandemias",
    "Papa",
    "Papel de la mujer",
    "Parcelas",
    "Parques nacionales",
    "Participación",
    "Participación comunitaria",
    "Participación de agricultores",
    "Participación de la mujer",
    "Participación pública",
    "Pequeñas explotaciones",
    "Pequeños agricultores",
    "Pequeños agricultores",
    "Pequeños productores",
    "Permacultura",
    "Pescadores",
    "Peste porcina africana",
    "Peste porcina clásica",
    "Phytophthora infestans",
    "Piscicultura",
    "Pisum sativum",
    "Pitahaya",
    "Plagas",
    "Plagas de animales",
    "Plagas de plantas",
    "Plaguicidas",
    "Plan de ordenamiento territorial",
    "Planes de acción",
    "Planificación de la explotación",
    "Plantas",
    "Plantas medicinales",
    "Plantas procesadoras",
    "Plátano fruta",
    "Población rural",
    "Pobreza",
    "Pobreza rural",
    "Política",
    "Política agraria",
    "Política agrícola",
    "Política alimentaria",
    "Política de aguas",
    "Política de comercialización",
    "Política de desarrollo",
    "Políticas",
    "Políticas públicas",
    "Políticas públicas",
    "Políticas públicas",
    "Pozos",
    "Prácticas agrícolas",
    "Preservación",
    "Prevención de enfermedades",
    "Problemas sociales",
    "Procedimientos de operación estándares",
    "Procedimientos operativos normalizados en materia de higiene",
    "Procesamiento",
    "Procesamiento de alimentos",
    "Procesos",
    "Producción alimentaria",
    "Producción animal",
    "Producción avícola",
    "Producción de biomasa",
    "Producción de carne",
    "Producción de cultivos básicos",
    "Producción de huevos",
    "Producción de madera",
    "Producción de productos agrícolas",
    "Producción de semillas",
    "Producción forestal",
    "Producción lechera",
    "Producción pecuaria",
    "Producción pesquera",
    "Producción potencial",
    "Producción sostenible",
    "Producción vegetal",
    "Productividad",
    "Productividad agrícola",
    "Productos agrícolas",
    "Productos de origen vegetal",
    "Programas",
    "Programas de desarrollo",
    "Promoción",
    "Propiedad colectiva",
    "Protección",
    "Proteínas de origen animal",
    "Protocolos",
    "Proyectos de desarrollo",
    "Proyectos de investigación",
    "Proyectos pilotos",
    "Puebla",
    "Pueblos indígenas",
    "Pyme",
    "Queso",
    "Quinua",
    "Radio (medio de comunicación)",
    "Raza bovina",
    "Reacción en cadena de la polimerasa",
    "Reciclaje",
    "Recuperación",
    "Recursos económicos",
    "Recursos forestales",
    "Recursos hídricos",
    "Recursos humanos",
    "Recursos naturales",
    "Recursos renovables",
    "Redes",
    "Reducción de emisiones",
    "Reducción de riesgos",
    "Reducción del riesgo de desastres",
    "Reemplazo de la reina",
    "Reforma agraria",
    "Registro catastral",
    "Registro digital",
    "Reglamentaciones",
    "Regulaciones del mercado",
    "Regularización de tierras",
    "Rehabilitación",
    "Relaciones internacionales",
    "Rendimiento de cultivos",
    "Reproduction animal",
    "Residuos",
    "Residuos de plaguicidas",
    "Resiliencia",
    "Resiliencia al clima",
    "Resiliencia de los ecosistemas",
    "Respuesta de defensa",
    "Restauración",
    "Restauración de humedales",
    "Restauración de los ecosistemas",
    "Riego",
    "Riego por goteo",
    "Riesgo",
    "Riesgos climáticos",
    "Riesgos para la salud",
    "Salud",
    "Salud pública",
    "Sanidad alimentaria",
    "Sanidad animal",
    "Sanidad vegetal",
    "Secretarías",
    "Sector agrario",
    "Sector agro alimentario",
    "Sector agroalimentario",
    "Sector de la producción",
    "Sector forestal",
    "Sector pesquero",
    "Sector privado",
    "Sector público",
    "Seguimiento y evaluación",
    "Seguridad",
    "Seguridad alimentaria",
    "Seguridad alimentaria en el hogar",
    "Seguridad nutricional",
    "Seguro agrario",
    "Semilla de café",
    "Semillas",
    "Semillero",
    "Seminarios",
    "Sensibilización",
    "Sequía",
    "Servicios agrícolas",
    "Servicios de apoyo",
    "Servicios de extensión",
    "Servicios de información",
    "Servicios de información mercado",
    "Servicios de los ecosistemas",
    "Servicios públicos",
    "Servicios sociales",
    "Sica",
    "Silvicultura",
    "Silvicultura comunitaria",
    "Sistema de extensión",
    "Sistema de información geográfica",
    "Sistema de organización del conocimiento",
    "Sistema de riego (método)",
    "Sistema de seguimiento",
    "Sistemas agroalimentarios",
    "Sistemas agroforestales",
    "Sistemas alimentarios",
    "Sistemas de alimentación",
    "Sistemas de cría",
    "Sistemas de información",
    "Sistemas de innovación",
    "Sistemas de innovación agrícola",
    "Sistemas de producción",
    "Sistemas de semillas",
    "Sistemas de vigilancia",
    "Sistemas integrados de producción agropecuaria",
    "Sistemas pecuarios",
    "Sistemas silvopastorales",
    "Soberanía alimentaria",
    "Soja",
    "Sostenibilidad",
    "Suelo",
    "Suelo agrícola",
    "Suelos cultivables",
    "Suministro de alimentos",
    "Tabaco",
    "Tabasco",
    "Talleres",
    "Técnicas de cultivo",
    "Tecnología",
    "Tecnología agrícola",
    "Tecnología de comunicación",
    "Tecnología de producción",
    "Tecnología de protección",
    "Tecnología digital",
    "Tecnologías para la información y la comunicación (tic)",
    "Teledetección",
    "Teledetección aérea",
    "Tenencia de la tierra",
    "Tephritidae",
    "Territorios",
    "Transferencia de tecnología",
    "Transparencia del mercado",
    "Trazabilidad",
    "Trazabilidad de productos",
    "Trenes",
    "Tubérculo",
    "Tunas",
    "Turismo",
    "Turismo rural",
    "Unión europea",
    "Uso de la tierra",
    "Uso de tierras forestales",
    "Uso del agua",
    "Utilización de la tierra",
    "Utilización sostenible",
    "Vacunación",
    "Variabilidad climática",
    "Variedad (taxones)",
    "Variedades cultivadas",
    "Vegetación",
    "Ventas",
    "Verduras",
    "Veterinarios",
    "Viabilidad económica",
    "Vigilancia",
    "Vigilancia de enfermedades",
    "Vigilancia de plagas",
    "Virus de la influenza aviar",
    "Virus de la peste porcina africana",
    "Vivienda",
    "Vulnerabilidad",
    "Zonas ecológicas",
    "Zonas protegidas",
    "Zonas rurales",
    "Zonas silvestres",
    "Zonas urbanas"
];
