
import re
import json

html_content = """
<option value="2658">Academia Nacional de Ingenier&#237;a y Habitat - ANIH</option>
<option value="2816">ACCESO - </option>
<option value="2641">Acceso Oferta Local-Productos de El Salvador S.A. de C.V. -  AOL</option>
<option value="2">Agencia Andaluza de Cooperaci&#243;n Internacional para el Desarrollo - AACID</option>
<option value="166">Ag&#234;ncia Brasileira de Coopera&#231;&#227;o - ABC</option>
<option value="2389">Agencia de Regulaci&#243;n y Control Fito y Zoosanitario - </option>
<option value="106">Agencia Ecuatoriana de Aseguramiento de la Calidad para el Agro - AGROCALIDAD</option>
<option value="3">Agencia Espa&#241;ola de Cooperaci&#243;n Internacional para el Desarrollo - AECID</option>
<option value="99">Ag&#234;ncia Nacional de &#193;guas - ANA</option>
<option value="164">AgResearch - </option>
<option value="139">Agriculture and Agri-Food Canada - AAFC </option>
<option value="1302">AGRITERRA - </option>
<option value="2633">Alianza para el Emprendimiento e Innovaci&#243;n - AEI</option>
<option value="2718">Andes Amazon Fund - AAF</option>
<option value="2620">Application Europ&#233;enne de Technologies et de Services - AETS</option>
<option value="2624">Asociaci&#243;n Costarricense de Biogas - </option>
<option value="2927">Asociaci&#243;n de Mujeres Afroecuatorianas Timbir&#233; en el Futuro - AMATIF</option>
<option value="2811">Asociaci&#243;n Espa&#241;ola de Consultoras de Cooperaci&#243;n para el Desarrollo - CONSULTED</option>
<option value="118">Asociaci&#243;n Nacional del Caf&#233; - ANACAFE</option>
<option value="2355">Asociaci&#243;n Promotora de Combustibles Renovables - ACR</option>
<option value="2404">Associa&#231;ao Brasileira de Criadores de Su&#237;nos - ABCS</option>
<option value="1284">Associa&#231;ao Brasileira de Prote&#237;na Animal - ABPA</option>
<option value="2362">Australian Agency for International Development  - AUSAID</option>
<option value="110">Australian High Commission - AHC</option>
<option value="2746">Australian High Commission&#39;s Direct Aid Program - DAP</option>
<option value="2818">Autoridad del Canal de Panam&#225; - ACP</option>
<option value="2871">Banco Agr&#237;cola de la Rep&#250;blica Dominicana - BAGRICOLA</option>
<option value="2699">Banco de Desarrollo Agropecuario - BDA</option>
<option value="6">Banco de Desarrollo de Am&#233;rica Latina y el Caribe - CAF</option>
<option value="8">Banco Internacional de Reconstrucci&#243;n y Fomento - BIRF</option>
<option value="2667">Barbados Agricultural Society  - BAS</option>
<option value="165">Barbados Environmental Conservation Trust - BECT</option>
<option value="1269">Basic Needs Trust Fund Guyana - BNTF</option>
<option value="112">Bayer AG - </option>
<option value="2719">Bezos Earth Fund - </option>
<option value="2810">BIOHUBCAT - </option>
<option value="2311">British Embassy to Peru - </option>
<option value="247">Bundesministerium f&#252;r Umwelt, Naturschutz, nukleare Sicherheit und Verbraucherschutz - BMUV</option>
<option value="2408">C&#225;mara Argentina de Bioinsumos - CABIO</option>
<option value="1296">C&#225;mara de la Industria Aceitera Argentina  - CIARA</option>
<option value="2682">C&#225;mara Nacional de Agricultura y Agroindustria - CNAA</option>
<option value="12">Caribbean Agricultural Research and Development Institute  - CARDI</option>
<option value="2666">Caribbean Agriculture Health and Food Safety - CAHFSA</option>
<option value="225">Caribbean Biodiversity Fund - CBF</option>
<option value="2411">Caribbean Community  - CARICOM</option>
<option value="1283">Caribbean Community Climate Change Centre - CCCCC</option>
<option value="2312">Caribbean Development Bank - CDB</option>
<option value="2415">Catholic Relief Service - CRS</option>
<option value="132">Centre de Coop&#233;ration Internationale en Recherche Agronomique pour le D&#233;veloppement - CIRAD </option>
<option value="2329">Centre for Agriculture and Bioscience International - CABI</option>
<option value="131">Centro Agron&#243;mico Tropical de Investigaci&#243;n y Ense&#241;anza - CATIE </option>
<option value="14">Centro de Competitividad de la Regi&#243;n Occidental - CECOMRO</option>
<option value="117">Centro Internacional de Agricultura Tropical - CIAT</option>
<option value="222">Centro Internacional de la Papa - CIP</option>
<option value="2691">Centro Internacional de Mejoramiento de Ma&#237;z y Trigo - CIMMYT</option>
<option value="1301">Centro Nacional de Tecnolog&#237;a Agropecuaria y Forestal - CENTA</option>
<option value="2345">Chileprunes Association AG - </option>
<option value="2813">Clarence Fitzroy Bryant College - CFBC</option>
<option value="2352">Coalici&#243;n Costarricense de Iniciativas de Desarrollo  - CINDE</option>
<option value="2424">Comisi&#243;n Econ&#243;mica para Am&#233;rica Latina y el Caribe  - CEPAL</option>
<option value="138">Comisi&#243;n Interamericana de Agricultura Org&#225;nica - CIAO</option>
<option value="2887">Comisi&#243;n Nacional de Fomento Rural - CNFR</option>
<option value="156">Comit&#233; de Sanidad Vegetal - COSAVE</option>
<option value="2426">Comit&#233; Veterinario Permanente del Cono Sur  - CVP</option>
<option value="2429">Confederaci&#243;n de Asociaciones de Productores Agropecuarios de Venezuela  - FEDEAGRO</option>
<option value="17">Consejo Agropecuario Centroamericano - CAC</option>
<option value="2645">Consejo Agropecuario del Sur - CAS</option>
<option value="228">Consejo Nacional Agropecuario - CNA</option>
<option value="2808">Consejo Nacional de Producci&#243;n - CNP</option>
<option value="120">Consejo Salvadore&#241;o del Caf&#233; - CSC</option>
<option value="2342">Consorcio de Gobiernos Aut&#243;nomos Provinciales de Ecuador - CONGOPE</option>
<option value="2747">Consultative Group for International Agricultural Research - CGIAR</option>
<option value="2628">Cooperativa Campesina Cuncum&#233;n - </option>
<option value="215">Cooperativa de Productores y Procesadores de Cercas Vivas de Pi&#241;&#243;n - Cooprocerna</option>
<option value="195">Coordenadoria de Defesa Agropecu&#225;ria do Estado de S&#227;o Paulo - CDA</option>
<option value="162">Coordinadora Latinoamericana y del Caribe de Peque&#241;os Productores y Trabajadores de Comercio Justo - CLAC</option>
<option value="20">Corporaci&#243;n Andina de Fomento - CAF</option>
<option value="2730">Corporaci&#243;n Colombiana de Investigaci&#243;n Agropecuaria - AGROSAVIA</option>
<option value="216">Corporaci&#243;n Consorcio Lechero de Chile - </option>
<option value="2438">Corporaci&#243;n Ganadera - CORFOGA</option>
<option value="2856">Corporaci&#243;n GANSO  - </option>
<option value="2613">Corporaci&#243;n para el Desarrollo del Tiltil - </option>
<option value="237">CORTEVA Agriscience - </option>
<option value="168">Croplife Latin America - </option>
<option value="1287">DAI Global UK Limited - </option>
<option value="2609">Department of Environment and Climate Change of Guyana - DECC</option>
<option value="97">Deutsche Gesellschaft f&#252;r Internationale Zusammenarbeit - GIZ</option>
<option value="22">Direcci&#243;n de Ciencia y Tecnolog&#237;a Agropecuaria - DICTA</option>
<option value="1307">Direcci&#243;n de Programas y Proyectos Sectoriales y Especiales  - DIPROSE</option>
<option value="2315">E&amp;A Consultants Inc.  - EACI</option>
<option value="140">Elanco Animal Health Inc.  -   </option>
<option value="1293">Embajada de Estados Unidos en Bolivia - </option>
<option value="171">Empresa Baiana de Aguas e Saneamento S.A. - EMBASA</option>
<option value="142">Empresa Brasileira de Pesquisa Agropecu&#225;ria - EMBRAPA</option>
<option value="104">Empresa El&#233;ctrica Provincial Gal&#225;pagos S.A. - Elecgal&#225;pagos</option>
<option value="84">Energising Development - EnDev</option>
<option value="173">Equinoccio - </option>
<option value="1290">Escuela Nacional de Agricultura “Roberto Qui&#241;&#243;nez” - ENA</option>
<option value="29">European Union  - EU</option>
<option value="1278">Facultad de Ciencias Agron&#243;micas de la Universidad de Chile - </option>
<option value="1294">Federaci&#243;n Nacional de Cultivadores de Cereales, Leguminosas y Soya - FENALCE</option>
<option value="2846">Federaci&#243;n Nacional de Productores de Ganado Bovino  - FEDECARNE</option>
<option value="2450">Federaci&#243;n Panamericana de Lecher&#237;a - FEPALE</option>
<option value="2883">Federaci&#243;n Uruguaya de grupos CREA - FUCREA</option>
<option value="175">Fertilizer Canada - </option>
<option value="1300">Fideicomiso Junto a T&#237;  -    </option>
<option value="2354">Finance in Motion - </option>
<option value="134">Financiere Agricole du Quebec Development International - FADQDI</option>
<option value="2376">Fine Cacao and Chocolate Institute - FCCI</option>
<option value="2866">Fondo de Inversi&#243;n Ambiental Sostenible - FIAS</option>
<option value="2634">Fondo de Promoci&#243;n de las &#193;reas Naturales Protegidas del Per&#250; - PROFONANPE</option>
<option value="31">Fondo Especial para el Desarrollo Agropecuario - FEDA</option>
<option value="2324">Fondo Financiero para el Desarrollo de la Cuenca del Plata - FONPLATA   </option>
<option value="241">Fondo Italo Ecuatoriano para el Desarrollo Sostenible - FIEDS</option>
<option value="176">Fondo Nacional de Desarrollo Cient&#237;fico, Tecnol&#243;gico y de Innovaci&#243;n Tecnol&#243;gica - FONDECYT</option>
<option value="2828">Fondo para Desarrollo de los Pueblos Ind&#237;genas de Am&#233;rica Latina y el Caribe -  FILAC</option>
<option value="2368">Fondo Regional de Tecnolog&#237;a Agropecuaria - FONTAGRO</option>
<option value="33">Food and Agriculture Organization of the United Nations  - FAO </option>
<option value="177">Food and Drug Administration of the US - FDA</option>
<option value="210">Foreign Agricultural Service&#39;s Office of Capacity Building and Development - FAS</option>
<option value="2619">Formaci&#243;n para el Desarrollo y la Inserci&#243;n - DEFOIN</option>
<option value="1270">Forum for International Trade Training - FITT</option>
<option value="2369">Fundaci&#243;n &quot;La Caixa&quot; -    </option>
<option value="2618">Fundaci&#243;n Alter-Eco - Alter-Eco</option>
<option value="2457">Fundaci&#243;n BBVA para las Microfinanzas - </option>
<option value="2459">Fundaci&#243;n Coordinadora Espa&#241;ola de ONGs  - CODESPA</option>
<option value="2621">Fundaci&#243;n Costa Rica-Estados Unidos para la Cooperaci&#243;n  - CRUSA</option>
<option value="178">Fundaci&#243;n de la Universidad Nacional de Villa Mar&#237;a - UNVM</option>
<option value="2721">Fundaci&#243;n Internacional y para Iberoam&#233;rica de Administraci&#243;n y Pol&#237;ticas P&#250;blicas - FIIAPP</option>
<option value="2743">Fundaci&#243;n Juana de Vega - FDJV</option>
<option value="2926">Fundaci&#243;n Mango Ecuador - </option>
<option value="2360">Fundaci&#243;n Nuestra Se&#241;ora del Camino - FNSC</option>
<option value="179">Fundaci&#243;n para la Innovaci&#243;n Agraria - FIA</option>
<option value="2741">Fundaci&#243;n para la Promoci&#243;n e Investigaci&#243;n de Productos Andinos - PROINPA</option>
<option value="2468">Fundaci&#243;n Servicio para el Agricultor - FUSAGRI</option>
<option value="2335">G&#233;nome Qu&#233;bec - </option>
<option value="2319">Global Affairs Canada/Affaires Mondiales Canada - GAC</option>
<option value="2384">Global Crop Diversity Trust - </option>
<option value="37">Global Environment Facility - GEF</option>
<option value="2639">Global Methane Hub - GMH</option>
<option value="2476">Global Water Partnership - Caribbean - GWP</option>
<option value="2892">Gobierno Aut&#243;nomo Descentralizado de la Provincia de Chimborazo - </option>
<option value="2477">Gobierno Aut&#243;nomo Descentralizado de la Provincia de Esmeraldas - </option>
<option value="2900">Gobierno Aut&#243;nomo Descentralizado de la Provincia de Pichincha - </option>
<option value="1310">Gobierno Aut&#243;nomo Descentralizado Municipal del Cant&#243;n de Bol&#237;var -   </option>
<option value="1281">Gobierno Aut&#243;nomo Descentralizado Provincial de Guayas - </option>
<option value="181">Gobierno Aut&#243;nomo Descentralizado Provincial de Manab&#237;  - </option>
<option value="2483">Gobierno Provincial de Loja - </option>
<option value="2717">Gordon and Betty Moore Foundation - </option>
<option value="2322">Gran Tierra Energy Inc.  - </option>
<option value="44">Green Climate Fund - GCF</option>
<option value="2380">Grenada Bureau of Standards - GDBS</option>
<option value="2829">Grenada Investment Development Corporation - GIDC</option>
<option value="2610">Heineken Brasil - </option>
<option value="1299">Hidroalto Generaci&#243;n de Energ&#237;a S.A. - </option>
<option value="226">IAMovement - IAMV</option>
<option value="2626">Improving Economies for Stronger Communities - IECS</option>
<option value="2706">Innovaciones Tecnol&#243;gicas Agropecuarias S.A. - INTeA</option>
<option value="2349">Instituto Agrario Dominicano - IAD</option>
<option value="2657">Instituto de Ciencia y Tecnolog&#237;as Agr&#237;colas de Guatemala - ICTA</option>
<option value="230">Instituto de Desarrollo Agropecuario - INDAP</option>
<option value="183">Instituto de Investigaciones Agropecuarias  - INIA</option>
<option value="2698">Instituto de Seguro Agropecuario - ISA</option>
<option value="121">Instituto del Caf&#233; de Costa Rica - ICAFE</option>
<option value="2494">Instituto Dominicano de Investigaciones Agropecuarias y Forestales - IDIAF</option>
<option value="119">Instituto Dominicano del Caf&#233; - INDOCAFE</option>
<option value="122">Instituto Hondure&#241;o del Caf&#233; - IHCAFE</option>
<option value="2495">Instituto Italo Latinoamericano - IILA</option>
<option value="113">Instituto Nacional de Aprendizaje - INA</option>
<option value="143">Instituto Nacional de Carnes  - INAC</option>
<option value="2497">Instituto Nacional de Colonizaci&#243;n  - INC</option>
<option value="2498">Instituto Nacional de Econom&#237;a Social - INAES</option>
<option value="161">Instituto Nacional de Innovaci&#243;n Agraria - INIA</option>
<option value="2725">Instituto Nacional de Innovaci&#243;n y Transferencia en Tecnolog&#237;a Agropecuaria de Costa Rica - INTA</option>
<option value="2499">Instituto Nacional de Investigaci&#243;n Agropecuaria - INIA</option>
<option value="2374">Instituto Nacional de Investigaci&#243;n y Desarrollo Pesquero  - INIPED</option>
<option value="185">Instituto Nacional de Investigaciones Agropecuarias  - INIAP</option>
<option value="127">Instituto Nacional de Investigaciones Forestales, Agr&#237;colas y Pecuarias - INIFAP </option>
<option value="2885">Instituto Nacional de Semillas - INASE</option>
<option value="235">Instituto Nacional de Tecnolog&#237;a Agropecuaria - INTA</option>
<option value="2884">Instituto Nacional de Vitivinicultura&#160; - INAVI</option>
<option value="123">Instituto Nicarag&#252;ense de Tecnolog&#237;a Agropecuaria - INTA</option>
<option value="2323">Instituto Paraguayo de Tecnolog&#237;a Agraria - IPTA</option>
<option value="2505">Instituto Plan Agropecuario - IPA</option>
<option value="7">Inter-American Development Bank - IDB</option>
<option value="2510">International Cocoa Organization - ICCO</option>
<option value="233">International Coffee Organization - ICO</option>
<option value="239">International Consortium on Applied Bieconomy Research  - ICABR</option>
<option value="2512">International Food Policy Research Institute  - IFPRI</option>
<option value="50">International Fund for Agricultural Development - IFAD</option>
<option value="2544">International Labour Organization - ILO</option>
<option value="1280">International Organization for Migration - IOM</option>
<option value="184">International Potash Institute - IPI</option>
<option value="2350">International Trade Center - ITC</option>
<option value="2638">International Union for Conservation of Nature - IUCN</option>
<option value="38">Internationale Klimaschutzinitiative - IKI</option>
<option value="1297">ITAIPU Binacional - </option>
<option value="125">Jamaica Agricultural Commodities Regulatory Authority - JACRA</option>
<option value="1274">Japan International Cooperation Agency - JICA</option>
<option value="1311">Jefatura de Gabinete de Ministros de la Rep&#250;blica Argentina - </option>
<option value="124">Junta Nacional del Caf&#233;  - JNC</option>
<option value="2370">Kangwon National University - KNU</option>
<option value="1264">Korea Institute for Development Strategy - KDS</option>
<option value="2627">Korea-Latin America Food &amp; Agriculture Cooperation Initiative  - </option>
<option value="218">Korean International Cooperation Agency  - KOICA</option>
<option value="214">Kreditanstalt f&#252;r Wiederaufbau - KfW</option>
<option value="2320">LATAC Enquiry Hub - Department for International Trade - </option>
<option value="2932">MASSY stores - </option>
<option value="2310">McKnight Foundation - </option>
<option value="1277">Mesa Argentina de Carne Sustentable - MACS</option>
<option value="238">Microsoft Corporation - </option>
<option value="1279">Minist&#232;re de l&#39;Agriculture, des Ressources Naturelles et du D&#233;veloppement Rural d&#39; Haiti - MARNDR</option>
<option value="2668">Minist&#232;re de la Sant&#233; Publique et de la Population d&#39;Ha&#239;ti - MSPP</option>
<option value="243">Ministerie van Landbouw, Veeteelt en Visserij  - </option>
<option value="2640">Ministerio Agropecuario de Nicaragua - </option>
<option value="245">Minist&#233;rio da Agricultura e Pecu&#225;ria do Brasil -   MAPA</option>
<option value="186">Minist&#233;rio da Cidadan&#237;a  -   </option>
<option value="2533">Minist&#233;rio da Integra&#231;&#227;o e do Desenvolvimento Regional  - MIDR</option>
<option value="2784">Minist&#233;rio da Pesca e Aquicultura - MPA</option>
<option value="2518">Minist&#233;rio das Rela&#231;&#245;es Exteriores - MRE</option>
<option value="252">Ministerio de Agricultura de Chile  - MINAGRI</option>
<option value="2519">Ministerio de Agricultura y Desarrollo Rural de Colombia - </option>
<option value="2521">Ministerio de Agricultura y Ganader&#237;a de Costa Rica - MAG</option>
<option value="2522">Ministerio de Agricultura y Ganader&#237;a de Ecuador - MAG</option>
<option value="227">Ministerio de Agricultura y Ganader&#237;a de El Salvador  - MAG</option>
<option value="187">Ministerio de Agricultura y Ganader&#237;a de Paraguay - MAG</option>
<option value="1275">Ministerio de Agricultura y Ganader&#237;a de Rep&#250;blica Dominicana - </option>
<option value="2520">Ministerio de Agricultura, Ganader&#237;a y Alimentaci&#243;n de Guatemala - MAGA</option>
<option value="155">Ministerio de Agricultura, Ganader&#237;a y Alimentaci&#243;n de la Provincia de Buenos Aires - MAGA</option>
<option value="229">Ministerio de Agricultura, Ganader&#237;a y Pesca de Argentina - MAGyP</option>
<option value="58">Ministerio de Agroindustria  - MINAGRO</option>
<option value="95">Ministerio de Agroindustria de la Provincia de Buenos Aires - MAIBA</option>
<option value="59">Ministerio de Ambiente de la Rep&#250;blica de Panam&#225; - MIAMBIENTE</option>
<option value="2650">Ministerio de Ambiente de Per&#250; - MINAM</option>
<option value="2532">Ministerio de Ambiente y Desarrollo Sostenible de Colombia - MINAMBIENTE</option>
<option value="2882">Ministerio de Ambiente&#160;de Uruguay - MA</option>
<option value="2662">Ministerio de Comercio Exterior y Turismo de Per&#250; - MINCETUR</option>
<option value="57">Ministerio de Desarrollo Agrario y Riego de Per&#250; - MIDAGRI</option>
<option value="61">Ministerio de Desarrollo Agropecuario de la Rep&#250;blica de Panam&#225; - MIDA</option>
<option value="2824">Ministerio de Desarrollo Productivo y Econom&#237;a Plural de Bolivia - </option>
<option value="2525">Ministerio de Desarrollo Rural y Tierras de Bolivia - MDRyT</option>
<option value="2612">Ministerio de Econom&#237;a de Argentina - </option>
<option value="2330">Ministerio de Educaci&#243;n de Argentina - </option>
<option value="2327">Ministerio de Educaci&#243;n P&#250;blica de Costa Rica  - MEP</option>
<option value="141">Ministerio de Energ&#237;a y Minas  -     </option>
<option value="111">Ministerio de Ganader&#237;a, Agricultura y Pesca de Uruguay - MGAP</option>
<option value="2530">Ministerio de Relaciones Exteriores y Culto de Costa Rica - RREE</option>
<option value="2357">Ministerio de Salud P&#250;blica y Asistencia Social de Guatemala  - MSPAS</option>
<option value="2827">Ministerio de Transporte de Colombia - </option>
<option value="2826">Ministerio de Vivienda, Ciudad y Territorio de Colombia - </option>
<option value="2663">Ministerio del Ambiente y Desarrollo Sostenible de Paraguay - MADES</option>
<option value="2344">Ministerio del Ambiente y los Recursos Naturales de Nicaragua  - MARENA</option>
<option value="212">Minist&#233;rio do Desenvolvimento e Assist&#234;ncia Social, Fam&#237;lia e Combate &#224; Fome  -   </option>
<option value="2534">Minist&#233;rio do Meio Ambiente e Mudan&#231;a do Clima  - MMA</option>
<option value="2623">Ministry of Agriculture and Agrifood of Canada - </option>
<option value="1268">Ministry of Agriculture of Guyana - </option>
<option value="2677">Ministry of Agriculture of Sant Lucia - MOA</option>
<option value="2535">Ministry of Agriculture, Fisheries and Barbuda Affairs - MAFBA</option>
<option value="2692">Ministry of Agriculture, Fisheries, Green and Blue Economy of Dominica - </option>
<option value="2683">Ministry of Agriculture, Fishing and Mining of Jamaica - MOAFM</option>
<option value="2729">Ministry of Agriculture, Food and Nutrition Security of Barbados - </option>
<option value="10">Ministry of Agriculture, Food Security and Enterprise of Belize - </option>
<option value="2679">Ministry of Agriculture, Forestry, Fisheries, Rural Transformation, Industry &amp; Labour of St. Vincent and the Grenadines - </option>
<option value="2644">Ministry of Agriculture, Land and Fisheries of Trinidad and Tobago - MALF</option>
<option value="2693">Ministry of Agriculture, Lands, Forestry, Fisheries &amp; Cooperatives of Grenada - MOALFC</option>
<option value="2678">Ministry of Agriculture, Marine Resources &amp; Cooperatives of St. Kitts and Nevis - MOA</option>
<option value="1267">Ministry of Agricuture and Marine Resources of Bahamas - </option>
<option value="72">Ministry of Education, Technological and Vocational Training of Barbados  - </option>
<option value="1298">Ministry of Environment and Housing of Bahamas - </option>
<option value="2865">Ministry of Finance of Bahamas - </option>
<option value="2365">Ministry of Health of Guyana - </option>
<option value="2714">Ministry of Primary Industries of New Zealand - MPI</option>
<option value="2744">Ministry of Tourism, Industry and Commerce of Guyana - MINTIC</option>
<option value="1295">Minor Use Foundation - MUF</option>
<option value="250">Misi&#243;n T&#233;cnica de Taiw&#225;n en Paraguay - </option>
<option value="1304">Municipalidad de Renaico - </option>
<option value="2629">National Bank of Dominica Ltd. - </option>
<option value="2331">NEC Proyecto Avanzar Rural - NECAR</option>
<option value="2731">New Venture Fund - NVF</option>
<option value="240">New Zealand Embassy to Chile - </option>
<option value="74">New Zealand High Commission for Barbados - </option>
<option value="2363">Newport-Fersan (Jamaica) Ltd. - NFJ</option>
<option value="2325">North Carolina State University - NCSU</option>
<option value="1252">N&#250;cleo de Estudos Agr&#225;rios e Desenvolvimento Rural do Ministerio do Desenvolvimiento Agrario - NEAD</option>
<option value="2635">OCA Global Consulting and Technical Advisory Services - </option>
<option value="2539">Ohio State University - OSU</option>
<option value="223">Oikocredit International - Oikocredit</option>
<option value="2734">Opus Seed LLC - </option>
<option value="2379">Organisation of Eastern Caribbean States  - OECS</option>
<option value="2351">Organismo Nacional de Sanidad Pesquera - SANIPES</option>
<option value="137">Organizaci&#243;n de Informaci&#243;n de Mercados de las Am&#233;ricas - OIMA</option>
<option value="2326">Organizaci&#243;n de los Estados Americanos  - OEA</option>
<option value="1285">Pan-American Development Foundation - PADF</option>
<option value="2822">Parques Nacionales Naturales de Colombia - </option>
<option value="249">Pontificia Universidad Cat&#243;lica de Valpara&#237;so - </option>
<option value="2356">Practical Action - </option>
<option value="2676">Presidencia de la Rep&#250;blica Dominicana - </option>
<option value="159">Programa Cooperativo para el Desarrollo Tecnol&#243;gico Agroalimentario y Agroindustrial del Cono Sur - PROCISUR</option>
<option value="2661">Programa Cooperativo Regional para el Desarrollo Tecnol&#243;gico y Modernizaci&#243;n de la Caficultura - PROMECAFE</option>
<option value="2341">Programa de Desarrollo de la Sanidad Agropecuaria  - PRODESA</option>
<option value="2359">Programa Nacional de Conservaci&#243;n de Bosques para la Mitigaci&#243;n del Cambio Clim&#225;tico - PNCBMCC</option>
<option value="2636">Programa Nacional de Desarrollo Rural Sostenible - PRONADERS</option>
<option value="96">Programa Nacional de Innovaci&#243;n Agraria  - PNIA</option>
<option value="1309">Project A+  - </option>
<option value="2858">Protected Areas Conservation Trust - PACT</option>
<option value="1288">Proyectos Energ&#233;ticos ECUAGESA -  ECUAGESA</option>
<option value="2643">RE:WILD Brazil - RE: WILD</option>
<option value="197">Red de Gesti&#243;n de la Innovaci&#243;n del Sector Agropecuario  - Red INNOVAGRO</option>
<option value="2616">Red Latinoamericana para Servicios de Extensi&#243;n Rural  - RELASER</option>
<option value="2855">Red Stripe - </option>
<option value="244">Registro Agrario Nacional - RAN</option>
<option value="1258">Rep&#250;blica de China (Taiw&#225;n) - </option>
<option value="2340">Rikolto International - </option>
<option value="2637">Rural Commerce - </option>
<option value="114">Safe and Secure Approaches in Field Environments course  - SSAFE</option>
<option value="1286">SAGA Commercial Group, S.A.  - </option>
<option value="2820">Saint Lucia National Conservation Fund - SLUNCF</option>
<option value="2348">Sandals Foundation - </option>
<option value="102">Secretaria da Agricultura Familiar do Minist&#233;rio do Desenvolvimento Agr&#225;rio  - SAF/MDA</option>
<option value="1282">Secretaria da Agricultura, Pecu&#225;ria, Produ&#231;&#227;o Sustent&#225;vel e Irriga&#231;&#227;o - Seapi</option>
<option value="115">Secretar&#237;a de Agricultura y Desarrollo Rural  - SADER</option>
<option value="193">Secretar&#237;a de Agricultura y Ganader&#237;a de Honduras - SAG</option>
<option value="1263">Secretar&#237;a de Agricultura, Ganader&#237;a y Pesca de Argentina  - </option>
<option value="1273">Secretar&#237;a de Agricultura, Ganader&#237;a y Pesca del Estado de Chiapas  - SAGyP</option>
<option value="76">Secretar&#237;a de Agricultura, Ganader&#237;a, Desarrollo Rural, Pesca y Alimentaci&#243;n  - SAGARPA</option>
<option value="77">Secretaria de Desenvolvimento Agr&#225;rio do Estado do Cear&#225; - SDA-CE</option>
<option value="196">Secretaria de Desenvolvimento Territorial do Minist&#233;rio do Desenvolvimento Agr&#225;rio - SDT</option>
<option value="199">Secretaria de Estado do Desenvolvimiento da Agropecu&#225;ria e da Pesca - SEDAP</option>
<option value="2552">Secretar&#237;a de Estado en los Despachos de Agricultura y Ganader&#237;a de Honduras - </option>
<option value="2815">Secretaria de Innovaci&#243;n de la Presidencia de El Salvador - </option>
<option value="78">Secretar&#237;a de Integraci&#243;n Econ&#243;mica Centroamericana - SIECA</option>
<option value="213">Secretaria de Recursos Hidricos do Ministerio do Meio Ambiente - </option>
<option value="153">Secretar&#237;a de Reforma Agraria, Recursos H&#237;dricos e Irrigaci&#243;n - SRARHI</option>
<option value="79">Secretar&#237;a del Agua de Ecuador - </option>
<option value="80">Secretaria do Extrativismo e Desenvolvimento Rural do Brasil - SEDR-MMA</option>
<option value="200">Secretaria do Planejamento do Estado do Piau&#237; - SEPLAN</option>
<option value="201">Secretar&#237;a Ejecutiva del Consejo Agropecuario Centroamericano  - SECAC</option>
<option value="103">Secretaria Especial de Agricultura Familiar e do Desenvolvimento Agr&#225;rio - SEAD</option>
<option value="1303">Secretar&#237;a Nacional de Ciencia, Innovaci&#243;n y Tecnolog&#237;a de la Rep&#250;blica de Panam&#225; - SENACYT</option>
<option value="203">Secretaria Nacional de Saneamento Ambiental do Ministerio das Cidades	 - SNS</option>
<option value="1289">Secretar&#237;a T&#233;cnica de la Circunscripci&#243;n Territorial Especial Amaz&#243;nica - STCTEA</option>
<option value="2557">Secretariado Uruguayo de la Lana - SUL</option>
<option value="2817">Semilla Nueva - </option>
<option value="2558">Servicio Agr&#237;cola y Ganadero de Chile - SAG</option>
<option value="130">Servicio Nacional de Calidad y Salud Animal de la Rep&#250;blica de Paraguay - SENACSA </option>
<option value="101">Servicio Nacional de Salud Animal de Costa Rica - SENASA</option>
<option value="2371">Servicio Nacional de Sanidad Agraria de Per&#250;  - SENASA</option>
<option value="2646">Servicio Nacional de Sanidad Agropecuaria e Inocuidad Alimentaria - SENASAG</option>
<option value="2372">Servicio Nacional de Sanidad y Calidad Agroalimentaria de Argentina   - SENASA</option>
<option value="204">Servicio Nacional de Sanidad, Inocuidad y Calidad Agroalimentaria de M&#233;xico - SENASICA</option>
<option value="2560">Servi&#231;o Florestal Brasileiro - SFB</option>
<option value="82">Sistema de Banca para el Desarrollo - SBD</option>
<option value="2617">Sistema de Integraci&#243;n Centroamericana - SICA</option>
<option value="2367">Social Innovation Cluster for Change - SIC4Change</option>
<option value="2867">Sociedad Fiduciaria de Desarrollo Agropecuario - Fiduagraria</option>
<option value="2611">Sparx Treinamento Em Desenvolvimento Profissional E Gerencial Ltda - </option>
<option value="2812">St Kitts and Nevis Association for Persons with Disabilities - SKNAPD</option>
<option value="2821">St. Vincent and the Grenadines Bureau of Standards - </option>
<option value="2825">Stockholm Environment Institute - SEI</option>
<option value="2338">Subsecretar&#237;a de Agricultura - SUBAGRI</option>
<option value="2382">Subsecretar&#237;a de Agricultura de Chile - </option>
<option value="2337">Sustainable Agriculture Network - SAN</option>
<option value="135">Swiss Agency for Development and Cooperation - SDC</option>
<option value="232">Swiss Association for the Development of Agriculture and Rural Areas - AGRIDEA</option>
<option value="1260">Swiss Intercooperation HELVETAS - HEVETAS</option>
<option value="2361">Taiwan Technical Mission - TTM</option>
<option value="2859">Team Barbuda United Development Association - Team B.U.D.A</option>
<option value="163">Technical Centre for Agricultural and Rural Cooperation - CTA</option>
<option value="2383">Technoserve Inc. - </option>
<option value="242">The Coca-Cola Export Corporation - </option>
<option value="1265">The Cropper Foundation - </option>
<option value="2313">The Guyana Economic Development Fund Inc. - GEDT</option>
<option value="2625">The NextGen Ag Impact Network - </option>
<option value="251">The Partnership Initiative for Sustainable Land Management - PISLM</option>
<option value="2854">U.S. Department of State - </option>
<option value="2577">UN Women  - </option>
<option value="2722">Unidad Agroalimentaria Metropolitana - UAM</option>
<option value="206">Unidad para el Cambio Rural - UCAR</option>
<option value="2317">Uni&#243;n Nacional de Avicultores - UNA</option>
<option value="2853">United Nations Convention to Combat Desertification - UNCCD</option>
<option value="1257">United Nations Development Programme  - UNDP</option>
<option value="2931">United Nations Educational, Scientific and Cultural Organization - UNESCO</option>
<option value="75">United Nations Environment Programme  - UNEP</option>
<option value="1291">United Nations Office for Project Services  - UNOPS</option>
<option value="2805">United Nations Office on Drugs and Crime - UNODC</option>
<option value="88">United States Agency for International Development - USAID</option>
<option value="231">United States Dairy Export Council - USDEC</option>
<option value="89">United States Department of Agriculture - USDA</option>
<option value="207">United States Department of Agriculture/Animal and Plant Health Inspection Service  - USDA/APHIS</option>
<option value="208">United States Department of Agriculture/Foreign Agricultural Service of the United States - USDA/FAS</option>
<option value="2648">Universidad Aut&#243;noma de Chapingo - UACH</option>
<option value="2886">Universidad Cat&#243;lica de Uruguay - UCU</option>
<option value="2659">Universidad Central de Venezuela - UCV</option>
<option value="2738">Universidad Central del Ecuador - UCE</option>
<option value="2742">Universidad de Investigaci&#243;n de Tecnolog&#237;a Experimental Yachay - UITEY</option>
<option value="2586">Universidad de la Rep&#250;blica Oriental del Uruguay - UDELAR</option>
<option value="2736">Universidad de Nari&#241;o - UDENAR</option>
<option value="2739">Universidad Estatal del Sur de Manab&#237; de Ecuador - UNESUM</option>
<option value="2364">Universidad Industrial de Santander - UIS</option>
<option value="2735">Universidad Nacional Agraria La Molina - UNALM</option>
<option value="209">Universidad Nacional de Colombia - UNAL</option>
<option value="2728">Universidad Nacional de Costa Rica - UNA</option>
<option value="2737">Universidad Nacional de la Loja - UNL</option>
<option value="2819">Universidad Tecnol&#243;gica de Panam&#225;  - UTP</option>
<option value="2597">Universidad Tecnol&#243;gica del Uruguay - UTEC</option>
<option value="1306">Universidad Tecnol&#243;gica Metropolitana - UTEM</option>
<option value="2642">University of California, Davis  - UCDavis</option>
<option value="2314">University of Liverpool - </option>
<option value="2328">University of Technology - UTech</option>
<option value="109">University of Tennessee - UTK</option>
<option value="1266">US Grains Council - </option>
<option value="217">Wake Network - WAKE</option>
<option value="2375">WELead Caribbean - </option>
<option value="2381">Wi! Uma Fu Sranan - Wi!</option>
<option value="2632">Windward Fund - </option>
<option value="2732">Woodrow Wilson International Center for Scholars (Wilson Center) - WWICS</option>
<option value="9">World Bank Group - WB</option>
<option value="126">World Coffee Research - WCR</option>
<option value="2614">World Environment Center - WEC</option>
<option value="2665">World Food Prize Foundation - WFP</option>
<option value="2615">World Organisation for Animal Health - WOAH</option>
<option value="116">World Resources Institute - WRI</option>
<option value="192">World Trade Organization - WTO</option>
<option value="2823">World Wildlife Fund - WWF</option>
<option value="2716">Wyss Foundation - </option>
"""

import html

matches = re.findall(r'<option value="(\d+|)">([^<]+)</option>', html_content)

partners = []
for id_val, name in matches:
    clean_name = html.unescape(name).strip()
    if not clean_name: continue
    # Basic rudimentary link guessing (it won't be perfect but better than nothing)
    url = "https://www.google.com/search?q=" + clean_name.replace(" ", "+") + "&btnI=1"
    
    partners.append({
        "id": id_val,
        "name": clean_name,
        "url": url # Default to a Lucky Search. I will override key ones later.
    })

# Write to a JSON file
with open("lib/counterparts_raw.json", "w", encoding="utf-8") as f:
    json.dump(partners, f, indent=2, ensure_ascii=False)

print(f"Extracted {len(partners)} partners.")
